#!/bin/bash

if [ "$#" == "0" ]; then
	#interactive
	echo "interactive mode"
	while read -p "   input name (ctrl-d to exit): " name; do
		[ "${name}" == "" ] && exit
		urpmq --provides $(urpmq --whatprovides "${name}") | sed -n '/pkgconfig/{s/\[.*//;p}'
	done
elif [ "$#" == "1" ]; then
	#one arg
	urpmq --provides $(urpmq --whatprovides $1) | sed -n '/pkgconfig/{s/\[.*//;p}'
else
	#more than one arg
	echo "you must specify one name, or no args for interactive mode"
	exit 1
fi

